name: Build & Review
on: [pull_request]

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  SERVICE_PORT: 80
  K8S_REQUEST_CPU: 1m
  K8S_REQUEST_RAM: 10Mi
  K8S_LIMIT_CPU: 10m
  K8S_LIMIT_RAM: 20Mi

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-review

  review:
    runs-on: ubuntu-latest
    needs: build
    name: Review
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        env:
          ENVIRONMENT_URL: https://${{ env.K8S_NAMESPACE }}.${{ env.BASE_DOMAIN }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-review
          K8S_SECRET_REACT_APP_ENVIRONMENT: 'review'
          K8S_SECRET_REACT_APP_OIDC_AUTHORITY: 'https://tunnistamo.${{ env.BASE_DOMAIN }}/'
          K8S_SECRET_REACT_APP_PROFILE_GRAPHQL: 'https://profiili-api.${{ env.BASE_DOMAIN }}/graphql/'
          K8S_SECRET_REACT_APP_OIDC_CLIENT_ID: ${{ env.K8S_NAMESPACE }}

      - name: Setup Tunnistamo
        uses: City-of-Helsinki/setup-tunnistamo-action@main
        with:
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW}}
          review_namespace: ${{ env.K8S_NAMESPACE }}
          api_scope: https://api.hel.fi/auth/helsinkiprofile
